version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/notes_db
    ports:
      - "8000:8000"
    networks:
      - backend

  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    depends_on:
      - fastapi
    environment:
      API_URL: http://fastapi:8000
      BOT_TOKEN: ${BOT_TOKEN}
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
